name: SimpleGM
api: [3.0.0, 4.0.0]
main: SimpleGM\Drama_Lvl1\Main
version: 1.0.0-BETA
author: Drama_Lvl1

commands:
  gm:
    description: SimpleGM - Ändere dein Gamemode
    permission: SimpleGM.use

permissions:
  SimpleGM.use:
    description: Man kann /gm
    default: op